# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cc365d0b0c181ca14bacab8f3a74287329cf86b88ec72e51f29ee2bc80b5306bd48eb91572503145f221045477e64f144282d3dbf8891ac18874f48b824953e

test:
  secret_key_base: 325c4a95e217ae9070bf837025556cc254cbb6f123596adccaa49123d1de6cbca3ceaef3270b5cff68cb19dfd31b57f323256fad81bcedc9eb91453550b05d17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
